os: linux
dist: bionic
python:
    - '3.6'
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install --no-install-recommends -y cmake cpanminus hunspell libhunspell-dev libperl-dev hunspell-en-gb nodejs npm perl python3-pip python3-setuptools python3-tk
    - cpanm local::lib
    - eval "$(perl -Mlocal::lib=$HOME/perl_modules)"
install:
    - "`which python3` -m pip install --upgrade attrs cookiecutter flake8 pysol_cards random2 six staticjinja"
    - cpanm -n Code::TidyAll::Plugin::Flake8 Code::TidyAll::Plugin::TSLint HTML::Spelling::Site HTML::T5 IO::All MooX MooX::late Perl::Critic Perl::Tidy Test::Code::TidyAll Test::File::Find::CaseCollide Test::HTML::Recursive::DeprecatedTags Test::HTML::Tidy::Recursive::Strict Test::TrailingSpace YAML::XS
    - ( cd .. && git clone https://github.com/shlomif/PySolFC && cd PySolFC && make all_games_html )
script:
    - ./gen-helpers
    - make test
cache:
    directories:
        - $HOME/perl_modules
