#!/usr/bin/env perl

use strict;
use warnings;
use 5.014;
use autodie;

use Carp       ();
use Path::Tiny qw/ path /;

sub _run_cli_command
{
    my ( $cmd, $err ) = @_;

    if ( system(@$cmd) )
    {
        say "Running [@$cmd] failed!";
        Carp::confess($err);
    }
    return;
}

_run_cli_command(
    [
        'cookiecutter', '-f', '--no-input',
        'gh:shlomif/cookiecutter--shlomif-latemp-sites',
        'project_slug=.',
    ],
    'cookiecutter failed.'
);

_run_cli_command(
    [ 'bash', 'bin/install-npm-deps.sh', ],
    'npm install failed.',
);

=begin removed

    _run_cli_command( [ "make", "--silent", "-f", "lib/make/build-deps/build-deps.mak" ],
    "build-deps failed!" );
_run_cli_command( [ $^X, './bin/gen-helpers-main.pl' ], "gen-helpers-main.pl failed." );

=end removed

=cut

path("Makefile")->spew_utf8("include lib/make/main.mak\n");

__END__

=head1 COPYRIGHT & LICENSE

Copyright 2018 by Shlomi Fish

This program is distributed under the MIT / Expat License:
L<http://www.opensource.org/licenses/mit-license.php>

=cut
